### ISSUE TITLE
Download all missing maps not working

### ISSUE THREAD

**Issue by face0xff** [Piotrekol/CollectionManager#21]
After providing the cookie, the download list opens (I assume this means the authentication was successful?). 
However, no download is being started; everything stays at 0%.

![image](https://user-images.githubusercontent.com/31146253/91641087-71f6aa80-ea22-11ea-9928-b4e7f66420ac.png)

Stopping and resuming downloads doesn't change anything.
Another weird thing is that the list shows 288 maps, but the main window says I am missing 481 map sets?

I'm using version 1.0.154.

**Comment by Piotrekol** [comment]
`Another weird thing is that the list shows 288 maps, but the main window says I am missing 481 map sets?`
Adressed in commit above 
![image](https://user-images.githubusercontent.com/4990365/91656420-e2e8a180-eab8-11ea-80ab-572ead8c2749.png)

As for download issue, I can not reproduce it

**Comment by face0xff** [comment]
> As for download issue, I can not reproduce it

Here are my steps:
- Open an .osdb collection (had the problem mentioned in #11 that was solved by uploading the collections to osustats and re-downloading them)
- Online -> Download all missing maps
- Select the "directory for saved beatmaps" (should I choose the Songs folder or a folder which contains the Songs folder? neither seems to solve the issue)
- Download beatmaps with video? -> No
- Authentication with credentials: doesn't work
- Authentication with cookie: which one is it? sometimes it works with osu_session, sometimes it works with remember_web_something
- Once authenticated, the Download List pops up and every download is stuck at 0%

Is there anything I did wrong? I also uploaded the [.osdb file](https://puu.sh/Goaji/b088f43345.osdb) if you think it might be the core of the problem.

**Comment by Piotrekol** [comment]
`should I choose the Songs folder or a folder which contains the Songs folder?`
doesn't matter, any folder will work
`Authentication with cookie: which one is it?`
You can pass all of them, but after checking just before writing this response, osu_session is enough to be able to download beatmaps.
Also, this window showing up means that it indeed passed osu auth.

Should be obvious, but are you able to download beatmaps via osu page?

**Comment by face0xff** [comment]
I am able to download beatmaps the usual way via the osu! website.
The output of https://osu.ppy.sh/home/download-quota-check is `{"quota_used":3}` after having tried to download a few maps. 

The newest build doesn't seem to fix the problem 😢

**Comment by AkiraTenchi** [comment]
I have the same issue

**Comment by DutchEllie** [comment]
Yeah, same here. I tried both authenticating using my username and password, as well as using the osu_session cookie. Curiously, the cookie authentication never seems to work the first time you try, it always gives a bad folder or login error and the username/password login always seems to freeze the program and then throw an exception containing the following:
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.CookieAwareWebClient.IsLoggedIn(String checkUrl, String stringToFind)
   at CollectionManagerExtensionsDll.Modules.DownloadManager.OsuDownloader.Login(LoginData loginData)
   at App.OsuDownloadManager.LogIn(LoginData loginData)
   at App.OsuDownloadManager.AskUserForSaveDirectoryAndLogin(IUserDialogs userDialogs, ILoginFormView loginForm)
   at App.SidePanelActionsHandler.DownloadAllMissing(Object sender, Object data)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
App
    Assembly Version: 1.0.154.0
    Win32 Version: 1.0.154
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/App.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Common
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/Common.DLL
----------------------------------------
GuiComponents
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/GuiComponents.DLL
----------------------------------------
CollectionManager
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/CollectionManager.DLL
----------------------------------------
CollectionManagerExtensionsDll
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/CollectionManagerExtensionsDll.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.8.0.0
    Win32 Version: 2.8.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/ObjectListView.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.2.23222
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
MusicPlayer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/MusicPlayer.DLL
----------------------------------------
NAudio
    Assembly Version: 1.7.3.0
    Win32 Version: 1.7.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/NAudio.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
SharpCompress
    Assembly Version: 0.23.0.0
    Win32 Version: 0.23.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/SharpCompress.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`
The exception itself states an "The operation has timed out" error. The cookie authenticating only works after supplying the wrong thing a couple times. Really weird

**Comment by Piotrekol** [comment]
instead of providing single cookie value, provide all of them https://i.imgur.com/SI2ZGP8.png

for what it is worth, map downloading using cookies method still works flawlessly on my side using current newest release.

**Comment by Aksumxd** [comment]
Managed to get the download working when using cookies, but when using account credentials the program freezes for ~2min and pops this out. (Basically the same as @DutchEllie )



```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.CookieAwareWebClient.IsLoggedIn(String checkUrl, String stringToFind)
   at CollectionManagerExtensionsDll.Modules.DownloadManager.OsuDownloader.Login(LoginData loginData)
   at App.OsuDownloadManager.LogIn(LoginData loginData)
   at App.OsuDownloadManager.AskUserForSaveDirectoryAndLogin(IUserDialogs userDialogs, ILoginFormView loginForm)
   at App.BeatmapListingActionsHandler.DownloadBeatmapsManaged(Object sender)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
App
    Assembly Version: 1.0.154.0
    Win32 Version: 1.0.154
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/App.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Common
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/Common.DLL
----------------------------------------
GuiComponents
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/GuiComponents.DLL
----------------------------------------
CollectionManager
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/CollectionManager.DLL
----------------------------------------
CollectionManagerExtensionsDll
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/CollectionManagerExtensionsDll.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.8.0.0
    Win32 Version: 2.8.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/ObjectListView.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.2.23222
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
MusicPlayer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/MusicPlayer.DLL
----------------------------------------
NAudio
    Assembly Version: 1.7.3.0
    Win32 Version: 1.7.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/NAudio.DLL
----------------------------------------
SharpCompress
    Assembly Version: 0.23.0.0
    Win32 Version: 0.23.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Collection%20Manager/SharpCompress.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Comment by eman1369a** [comment]
I am having the same issue. I am using windows 10 build 18363 on an alienware area51m. I initially tried the authentication using the username and password and then tried cookies. The only cookies that did not give me an error saying out of bounds was the g_id which I put in and the downloads window opened. I tried several times and sometimes it only took the osu session id.

![asd](https://user-images.githubusercontent.com/59575541/102608278-a5effb80-40f7-11eb-8265-595681a0e664.PNG)

 However all the downloads say 0/0Mb and 0% and does nothing. If you try the username and password option you don't even get this window only the JIT debugging notice and the error. Prior to this notice the application freezes gives the notice and then does nothing. 

![Capture](https://user-images.githubusercontent.com/59575541/102608090-54e00780-40f7-11eb-831a-10440f5e3f21.PNG)
